// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-Ew2r10l5rbyJXthUJxnkhav5m3OBgA0',
    appId: '1:796229084590:web:6f001ebe7c0988e072543f',
    messagingSenderId: '796229084590',
    projectId: 'study-plannner',
    authDomain: 'study-plannner.firebaseapp.com',
    storageBucket: 'study-plannner.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkReXhVWrzEmYPfvRsLAuSu22nTzFVfZM',
    appId: '1:796229084590:android:3cae5072abfc478372543f',
    messagingSenderId: '796229084590',
    projectId: 'study-plannner',
    storageBucket: 'study-plannner.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAL1lR0NsGIkrIBRpW_OhqhPzsU6l9DPe8',
    appId: '1:796229084590:ios:f049cf8aa958b4ee72543f',
    messagingSenderId: '796229084590',
    projectId: 'study-plannner',
    storageBucket: 'study-plannner.firebasestorage.app',
    iosBundleId: 'com.example.studyPlanner',
  );
}
